source 'https://rubygems.org'

gem 'rails', '4.1.8'
gem 'pg'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'foundation-rails'


gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',
group: :doc

gem 'spring',
group: :development
gem 'devise'

group :development, :test do
  gem 'rspec-rails'
  gem 'orderly'
  gem 'pry-rails'
  gem 'capybara'
  gem 'launchy'
  gem 'factory_girl_rails'
end
